name: Deploy to Azure App Service

on:
  push:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: rameshkoapp      # e.g., myapp-12345
  DOTNET_VERSION: '8.0.407'                 # Check exact version with `dotnet --version`
  PUBLISH_FOLDER: 'publish'

jobs:
  build-and-deploy:
    runs-on: widows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build and Publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o ${{ env.PUBLISH_FOLDER }}

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.rameshkoapp }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ${{ env.PUBLISH_FOLDER }}
