name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Authenticate to GCP
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json  # Persist env variable

      - name: Terraform Init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
        run: terraform init

      - name: Terraform Plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
        run: terraform apply -auto-approve

      # Example of using new environment variable outputS
      - name: Save Terraform Plan output
        run: echo "terraform_output=tfplan" >> $GITHUB_ENV
